### ISSUE TITLE
Different outputs when changing tensor_parallel_size from 1 to 2

### ISSUE THREAD

**Issue by cwdghh** [ndif-team/nnsight#631]
## Description

Hi, thank you for the great project.

I noticed that running the same code with different `tensor_parallel_size` settings produces different outputs in `nnsight`. Specifically, when I set `tensor_parallel_size=1` versus `tensor_parallel_size=2`, I get different results, even though the input and the rest of the code remain the same.

I am not sure whether this is expected behavior, a numerical difference caused by tensor parallelism, or a bug in the integration.

## Minimal reproducible example

```python
import torch
from nnsight.modeling.vllm import VLLM


@torch.inference_mode()
def main():
    
    # 1. Initialize the vLLM model
    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model: {model_path}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=2,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.8
    )

    prompt = "The Eiffel Tower is in the city of"
    output_token = " Paris"

    head_dim = 128

    token_id = vllm.tokenizer.encode(output_token)[0]

    # 3. perform intervention
    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            all_logits = list().save()
                
            l = 27
            for h in range(2):
                with tracer.invoke(prompt):
                    # input tensor
                    head_in = vllm.model.layers[l].self_attn.o_proj.input.clone()
                    
                    # head range
                    start = h * head_dim
                    end = (h + 1) * head_dim
                    
                    # modify the tensor
                    head_in[:, start:end] = 0
                    
                    # intervene
                    vllm.model.layers[l].self_attn.o_proj.input = head_in
                    
                    # save the logits
                    _logits = vllm.logits.output[-1, token_id].item().save()

                    all_logits.append(_logits)

    print(all_logits)


if __name__ == "__main__":
    main()
```

## Steps to reproduce

1. Run the code with `tensor_parallel_size=1`
2. Record the output
3. Run the exact same code with `tensor_parallel_size=2`
4. Compare the outputs

## Expected behavior

I expected the outputs to be identical, or at least very close, when only changing `tensor_parallel_size`.

## Actual behavior

The outputs are different between `tensor_parallel_size=1` and `tensor_parallel_size=2`.

### Output with `tensor_parallel_size=1`
```text
[16.484375, 16.5]
```

### Output with `tensor_parallel_size=2`
```text
[14.7734375, 0.1871337890625]
```

## Environment

- OS: Ubuntu 22.04.2 LTS
- Python: 3.10.12
- PyTorch: 2.9.1+cu128
- CUDA: 12.1
- nnsight: 0.6.2
- vllm: 0.15.1
- transformers: 4.57.6
- GPU: NVIDIA A800-SXM4-80GB

## Additional notes

- The same prompt/input is used in both runs.
- The only change is `tensor_parallel_size`.
- If this behavior is expected due to numerical differences in tensor parallel execution, it would be helpful to know whether `nnsight` guarantees deterministic or equivalent outputs across different tensor parallel sizes.

Please let me know if I should provide a more complete reproducible script or additional logs.

**Comment by Butanium** [comment]
I expect even interventionless stuff to be different. Have you tried raw vllm with different parallel size and check if generation at temperature =0 differ? I predict they will

**Comment by Butanium** [comment]
You can even query vllm to return logits

**Comment by cwdghh** [comment]
> I expect even interventionless stuff to be different. Have you tried raw vllm with different parallel size and check if generation at temperature =0 differ? I predict they will
>
> You can even query vllm to return logits

Thanks for your support and suggestion. I ran both a raw vLLM test and an NNsight test to compare the behavior more carefully.

## Summary

From raw vLLM alone, I do see a small numerical difference when changing `tensor_parallel_size` from 1 to 2 at `temperature=0`, but the generated token stays the same. That seems consistent with the expected numerical variation from tensor parallel execution.

However, when I run a similar test through `nnsight.modeling.vllm.VLLM`, the behavior under `tensor_parallel_size=2` looks qualitatively different: repeated identical invocations do not return stable logits, and some returned values are `0.0` or otherwise far from the `tensor_parallel_size=1` result. That seems hard to explain as normal TP-related numerical noise.

---

## 1. Raw vLLM baseline

Here is the raw vLLM test script:

```python
from vllm import LLM, SamplingParams


def main():
    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    tensor_parallel_size = 2   # manually set to 1 or 2
    prompt = "The Eiffel Tower is in the city of"
    target_token = " Paris"

    llm = LLM(
        model=model_path,
        tensor_parallel_size=tensor_parallel_size,
        dtype="float16",
        trust_remote_code=True,
        gpu_memory_utilization=0.8,
        enforce_eager=True,
    )

    tokenizer = llm.get_tokenizer()
    target_ids = tokenizer.encode(target_token, add_special_tokens=False)
    if len(target_ids) != 1:
        raise ValueError(f"{target_token!r} -> multiple tokens: {target_ids}")
    target_id = target_ids[0]

    sampling_params = SamplingParams(
        max_tokens=1,
        temperature=0.0,
        top_p=1.0,
        logprobs=20,
    )

    outputs = llm.generate([prompt], sampling_params)
    gen = outputs[0].outputs[0]
    step0_logprobs = gen.logprobs[0]

    print(f"tensor_parallel_size={tensor_parallel_size}")
    print(f"prompt={prompt!r}")
    print(f"generated={gen.text!r}")
    print(f"target_token={target_token!r}, target_id={target_id}")

    if target_id in step0_logprobs:
        obj = step0_logprobs[target_id]
        logprob = obj.logprob if hasattr(obj, "logprob") else float(obj)
        print(f"target_logprob={logprob:.6f}")
    else:
        print("target token not in returned top-k logprobs")


if __name__ == "__main__":
    main()
```

### Output with `tensor_parallel_size=1`

```text
tensor_parallel_size=1
prompt='The Eiffel Tower is in the city of'
generated=' Paris'
target_token=' Paris', target_id=12095
target_logprob=-0.616845
```

### Output with `tensor_parallel_size=2`

```text
tensor_parallel_size=2
prompt='The Eiffel Tower is in the city of'
generated=' Paris'
target_token=' Paris', target_id=12095
target_logprob=-0.618354
```

This difference is small, and the generated token is identical in both cases, so this looks like expected numerical variation in raw vLLM.

---

## 2. NNsight VLLM test

Here is the corresponding NNsight test script:

```python
import torch
from nnsight.modeling.vllm import VLLM


@torch.inference_mode()
def main():

    TENSOR_PARALLEL_SIZE = 1  # manually set to 1 or 2
    
    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model: {model_path}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=TENSOR_PARALLEL_SIZE,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.8
    )

    prompt = "The Eiffel Tower is in the city of"
    output_token = " Paris"

    token_id = vllm.tokenizer.encode(output_token)[0]

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            all_logits = list().save()
            
            for _ in range(8):
                with tracer.invoke(prompt):
                    _logits = vllm.logits.output[-1, token_id].item().save()
                    all_logits.append(_logits)

    print(f"tensor_parallel_size={TENSOR_PARALLEL_SIZE}")
    print(f"prompt={prompt!r}")
    print(f"generated={output_token!r}, token_id={token_id}")
    print(f"logits={all_logits}")


if __name__ == "__main__":
    main()
```

### Output with `tensor_parallel_size=1`

```text
tensor_parallel_size=1
prompt='The Eiffel Tower is in the city of'
generated=' Paris', token_id=12095
logits=[16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375]
```

### Output with `tensor_parallel_size=2`

```text
tensor_parallel_size=2
prompt='The Eiffel Tower is in the city of'
generated=' Paris', token_id=12095
logits=[0.472412109375, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.5, 16.5, 16.5]
```

---

## Why I suspect this may be on the NNsight side

The raw vLLM test shows only a very small difference in logprob across TP sizes, which seems normal.

By contrast, in the NNsight test under `tensor_parallel_size=2`:

1. Repeated identical `tracer.invoke(prompt)` calls do not produce stable logits.
2. The discrepancy is much larger than in raw vLLM:
   - raw vLLM: about `1e-3` difference in logprob
   - NNsight: values range from `0.0` / `0.4724` to `16.5`
3. This does not look like normal floating-point or reduction-order variation.
4. The number of collected values also appears inconsistent with the loop count, which may indicate an issue in tracing, dispatching, synchronization, or result collection.

Because of that, I suspect that the problem may be related to how NNsight captures or aggregates logits when `tensor_parallel_size > 1`, especially with `dispatch=True` and repeated `tracer.invoke(...)` calls inside the same trace context.

## Question

Could this be an issue with one of the following?

- logits capture under tensor parallelism
- synchronization / gathering when `dispatch=True`
- repeated `tracer.invoke(...)` calls within the same `trace(...)`
- `.save()` result collection across multiple invocations

If there is a preferred way to debug this further, I would be happy to run more tests.

**Comment by Butanium** [comment]
Thank you for the detailed report (cc @JadenFiotto-Kaufmanl

**Comment by JadenFiotto-Kaufman** [comment]
# Investigation Report: Issue #631 - Different outputs when changing tensor_parallel_size

## Summary

When performing interventions (e.g., head ablation) on `o_proj.input` with `tensor_parallel_size=2`, the results differ from `tensor_parallel_size=1`. The issue is **non-deterministic** -- the same test sometimes matches TP=1 and sometimes doesn't. The root cause appears to be that the extra NCCL `all_gather` collective operation introduced by NNsight's VLLMBatcher interacts poorly with vLLM's tensor-parallel execution, causing non-deterministic behavior on the first inference call.

## Environment

- **Model tested**: Qwen/Qwen2.5-0.5B (same architecture as reporter's Qwen2.5-7B)
- **vLLM**: 0.15.1 (v1 engine with `spawn` multiprocessing)
- **nnsight**: current main branch
- **GPUs**: NVIDIA A100 80GB x8

## Test Results

### Test 1: Basic TP parity (no intervention) -- PASS

Without any NNsight intervention, vLLM's TP=2 logits match TP=1:

| Run | TP=1 argmax | TP=2 argmax | Top-5 max diff |
|-----|------------|------------|----------------|
| 1-4 | 12095 | 12095 | 0.016 |

**Conclusion**: vLLM's baseline TP implementation is correct and deterministic.

### Test 2: Gather correctness (read o_proj.input) -- PASS

Reading `o_proj.input` with TP=2 produces correctly gathered tensors:

| Metric | TP=1 | TP=2 | Diff |
|--------|------|------|------|
| Shape | [10, 896] | [10, 896] | Match |
| Mean | -0.006797 | -0.006801 | 0.000004 |
| Norm | 25.2216 | 25.2153 | 0.0063 |

**Conclusion**: The VLLMBatcher's `all_gather` in `check_gathered()` correctly gathers sharded tensors.

### Test 3: Single head ablation -- FAIL (non-deterministic)

Each head ablation in a separate process (separate VLLM instance):

| Head | TP=1 | TP=2 | Diff | Status |
|------|------|------|------|--------|
| 0 | 16.953 | 16.938 | 0.016 | OK |
| 1 | 16.078 | 16.094 | 0.016 | OK |
| 2 | 16.797 | 16.797 | 0.000 | OK |
| 3 | 17.172 | 15.703 | 1.469 | **MISMATCH** |

The failing head changes across runs (non-deterministic).

### Test 4: Multi-invoke head ablation (issue repro) -- FAIL

Multiple invokes in a single trace (exactly as reported):

| Head | TP=1 | TP=2 | Diff | Status |
|------|------|------|------|--------|
| 0 | 16.953 | 15.234 | 1.719 | **MISMATCH** |
| 1 | 16.094 | 16.094 | 0.000 | OK |
| 2 | 16.797 | 16.797 | 0.000 | OK |
| 3 | 17.188 | 17.188 | 0.000 | OK |

### Test 5: Roundtrip (read + write back unchanged) -- PASS

Reading `o_proj.input` and writing it back without modification:

| TP=1 | TP=2 | Diff |
|------|------|------|
| 16.594 | 16.594 | 0.000 |

**Conclusion**: The gather-split roundtrip (including the `.input` setter flow) is bit-for-bit correct when no modification is made.

### Test 6: Warmup before ablation -- PASS

Running a no-intervention trace first, then performing ablation:

| TP=1 | TP=2 | Diff | Status |
|------|------|------|--------|
| 16.953 | 16.938 | 0.016 | OK |

**Conclusion**: A warmup trace eliminates the non-determinism. The diff of 0.016 is the expected TP precision difference (fp16 arithmetic).

### Test 7: Determinism analysis (head 0, 5 runs each)

**Without warmup:**
```
Run 0: 17.063  diff=0.109  OK
Run 1: 15.758  diff=1.195  MISMATCH
Run 2: 12.914  diff=4.039  MISMATCH
Run 3:  9.656  diff=7.297  MISMATCH
Run 4: 16.641  diff=0.313  OK
```

**With `torch.cuda.synchronize()` after `all_gather`:**
```
Run 0: 16.500  diff=0.453  OK
Run 1: 15.234  diff=1.719  MISMATCH
Run 2: 15.820  diff=1.133  MISMATCH
Run 3: 16.047  diff=0.906  MISMATCH
Run 4: 15.773  diff=1.180  MISMATCH
```

CUDA sync reduces the worst-case error (max diff from 7.3 to 1.7) but doesn't eliminate non-determinism.

## Root Cause Analysis

### What works correctly

1. **VLLMBatcher gather/split roundtrip**: `tensor_model_parallel_all_gather()` + `split_tensor_along_last_dim()` is mathematically correct and bit-for-bit identical to the original sharded tensor (Test 5).

2. **Batch group management**: `process_batch_groups()` correctly maps mediators to their tensor slices using `input_batch.req_ids` order.

3. **Hook ordering**: Hooks fire in the correct order:
   - `pre_input_hook` (VLLMBatcher, sets parallel/type state)
   - `input_hook` (Interleaver, handles mediator gather/intervention/swap)
   - `post_input_hook` (VLLMBatcher, splits gathered tensor back)

4. **`.input` getter/setter flow**: The `.input` property correctly unwraps `(args, kwargs)` to return `args[0]`, and the setter correctly reconstructs and swaps via `.inputs`.

### The non-determinism pattern

- **Baseline (no intervention)**: Always deterministic with TP=2 (Test 1)
- **Roundtrip (read + write back unchanged)**: Always deterministic (Test 5)
- **Intervention (modify + write back)**: Non-deterministic (Tests 3, 4, 7)
- **After warmup + intervention**: Deterministic (Test 6)

### Hypothesized root cause

The VLLMBatcher's `check_gathered()` introduces an **extra NCCL `all_gather` collective** into the model's forward pass that vLLM's TP execution was not designed for. This extra collective appears to interact with vLLM's first-call GPU initialization in a way that causes non-deterministic behavior:

1. **The extra `all_gather`** is called inside a PyTorch `forward_pre_hook`, which runs during the model's forward pass. Both TP ranks call it simultaneously (same hook, same module).

2. **First-call effect**: On the first inference after engine initialization, GPU state (NCCL internal buffers, cuBLAS workspace, CUDA stream scheduling) is not fully warmed up. The extra `all_gather` may change the order or timing of subsequent NCCL operations (e.g., `all_reduce` in `RowParallelLinear`), causing different floating-point results.

3. **Amplification**: Even small differences in intermediate values (< 0.016) are amplified through subsequent layers, producing large logit differences (1-7+) in the final output.

4. **Warmup eliminates the effect**: Running any trace first warms up the GPU/NCCL state, making subsequent operations deterministic.

### Why the roundtrip works but modification doesn't

The roundtrip test (read + write back unchanged) produces the same tensor as if no intervention occurred -- the module receives bit-for-bit the same input. So even if there's non-determinism in the `all_gather`, it doesn't matter because the tensor is unchanged.

With modification (zeroing a head), the module receives a different input. Any non-determinism in subsequent operations (which would cancel out with identical inputs) now produces different outputs.

## Potential Fixes

### 1. Automatic warmup (recommended short-term)

Add a warmup forward pass in the VLLM class when TP > 1, before executing user interventions:

```python
# In VLLM.__call__ or trace setup, when tp_size > 1:
if self._needs_warmup and self.tp_size > 1:
    # Run a dummy forward pass to warm up NCCL/CUDA
    self.vllm_entrypoint.generate(["warmup"], ...)
    self._needs_warmup = False
```

### 2. CUDA stream synchronization in check_gathered

Add `torch.cuda.synchronize()` after the `all_gather` in `check_gathered()`. This reduces the worst-case error but doesn't fully eliminate non-determinism:

```python
def check_gathered(self):
    if self.parallel and not self.gathered:
        if isinstance(self.current_module, RowParallelLinear):
            if self.type == "input":
                self.current_value = apply(
                    self.current_value,
                    lambda x: tensor_model_parallel_all_gather(x),
                    torch.Tensor,
                )
                torch.cuda.synchronize()  # Ensure gather is complete
        self.gathered = True
```

**Comment by JadenFiotto-Kaufman** [comment]
So it seems like a warmup run fixes things. I suppose I should add that by default when TP>1?

**Comment by cwdghh** [comment]
> So it seems like a warmup run fixes things. I suppose I should add that by default when TP>1?

@JadenFiotto-Kaufman Thank you for your support. I don't know if I understand your suggestion correctly. I tried adding a manual warmup call before entering the trace, using:

```python
samping_params = SamplingParams(temperature=0.0, max_tokens=16)
vllm.vllm_entrypoint.generate(["warmup"], sampling_params=samping_params)
```

and then ran the same repeated-invoke test again with `tensor_parallel_size=2`.

Here is the full script I used:

```python
import torch
from nnsight.modeling.vllm import VLLM
from vllm import SamplingParams


@torch.inference_mode()
def main():

    TENSOR_PARALLEL_SIZE = 2
    
    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model: {model_path}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=TENSOR_PARALLEL_SIZE,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.8
    )

    prompt = "The Eiffel Tower is in the city of"
    output_token = " Paris"

    token_id = vllm.tokenizer.encode(output_token)[0]

    # Warmup
    samping_params = SamplingParams(temperature=0.0, max_tokens=16)
    vllm.vllm_entrypoint.generate(["warmup"], sampling_params=samping_params)

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            all_logits = list().save()
            
            for _ in range(8):
                with tracer.invoke(prompt):
                    _logits = vllm.logits.output[-1, token_id].item().save()
                    all_logits.append(_logits)

    print(f"tensor_parallel_size={TENSOR_PARALLEL_SIZE}")
    print(f"prompt={prompt!r}")
    print(f"generated={output_token!r}, token_id={token_id}")
    print(f"logits={all_logits}")


if __name__ == "__main__":
    main()
```

The output is now:

```text
tensor_parallel_size=2
prompt='The Eiffel Tower is in the city of'
generated=' Paris', token_id=12095
logits=[2.931640625, 16.484375, 0.0, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375]
```

So manual warmup definitely improves the behavior compared with my previous run:
- the number of collected values is now correct,
- and most of the logits are now at the expected magnitude (`16.484375`).

However, the result is still not fully stable, since there are still anomalous values like `2.931640625` and `0.0` among otherwise identical repeated invocations.

So my current understanding is:

1. warmup helps, which suggests that part of the issue is indeed related to first-use initialization under TP > 1;
2. but warmup alone does not fully eliminate the problem;
3. this seems consistent with your second hypothesis that there may still be a synchronization issue around `all_gather` / `check_gathered()`.

Does that interpretation sound correct?

**Comment by JadenFiotto-Kaufman** [comment]
@cwdghh Hey could you do me a favor and try out this branch / PR? I think it fixes the problem. https://github.com/ndif-team/nnsight/pull/632

The problem seems to be, even adding hooks that do nothing to modules that are tensor parallelized causes the cuda operations to get out of sync of the nccl operations. I don't totally understand why as if all the shards have the same hooks, they should reach operations at similar times.

So this PR is pretty simple and just adds a cuda synchronization to the start of parallel modules. In my tests I wasnt able to reproduce the incorrect values after this patch. I also couldn't see a performance difference within the variance of the requests I did.

Let me know

**Comment by cwdghh** [comment]
@JadenFiotto-Kaufman Many thanks — I tested the latest branch / PR, and **it does appear** to fix the issue on my side. ❤️ 

I was able to get stable results with `tensor_parallel_size=2` after applying the patch. In my testing, I also found that I needed one additional CUDA synchronization before reading the logits in `GPUModelRunner.py`, specifically, add:

```python
# Additional synchronization for TP > 1
if get_tp_group().world_size > 1:
    torch.cuda.current_stream().synchronize()
```

before extracting logits

https://github.com/ndif-team/nnsight/blob/2cdd313f9669bbe1f4466b71e1ad5fbdeba4ec61/src/nnsight/modeling/vllm/model_runners/GPUModelRunner.py#L353-L363

After that, repeated identical invocations produced stable logits like:

```text
logits=[16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375, 16.484375]
```

So from my side, this does seem consistent with the issue being a CUDA/NCCL synchronization problem under tensor parallelism, and the synchronization-based fix appears to resolve it.

Thanks again for the quick fix.

**Comment by cwdghh** [comment]
@JadenFiotto-Kaufman  Thanks again — after applying the synchronization-related fix, the original unstable-logit issue seems resolved on my side.

However, I ran two additional tests and found what look like two separate remaining issues under `tensor_parallel_size=2`. These seem different from the original CUDA/NCCL synchronization problem, so I wanted to check whether you would prefer me to open new issues for them.

---

## 1. Reusing saved activations across traces causes a device mismatch error

I tested the following pattern:

- Trace 1: save a layer activation from one prompt
- Trace 2: reuse that saved activation to patch the same layer in a separate trace

Minimal reproduction:

```python
import torch
from nnsight.modeling.vllm import VLLM


@torch.inference_mode()
def main():
    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model: {model_path}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=2,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.6,
    )

    reference_prompt = "After John and Mary went to the store, Mary gave a bottle of milk to"
    layer_index = 0

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            with tracer.invoke(reference_prompt):
                head_in = vllm.model.layers[layer_index].self_attn.o_proj.input.clone().save()
                reference_activation_cache = head_in
    
    print(f"Reference activation shape: {reference_activation_cache.shape}")
    print(f"Reference activation device: {reference_activation_cache.device}")

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            with tracer.invoke(reference_prompt):
                vllm.model.layers[layer_index].self_attn.o_proj.input = reference_activation_cache.detach()
                logit = vllm.logits.output[-1, 0].item().save()

    print(logit)


if __name__ == "__main__":
    main()
```

This fails with a device mismatch error:

```text
RuntimeError: Expected all tensors to be on the same device, but got mat2 is on cuda:1, different from other tensors on cuda:0
```

This makes me suspect that activations saved from one trace are not being moved / sharded correctly when reused in a later trace under TP > 1.

---

## 2. Intervention results are still inconsistent between TP=1 and TP=2

I also tested a simple intervention where I zero out a slice of `self_attn.o_proj.input` corresponding to one attention head, and then compare the resulting logit for the token `" Paris"`.

Minimal reproduction:

```python
import argparse
import torch
from nnsight.modeling.vllm import VLLM


@torch.inference_mode()
def main():
    parser = argparse.ArgumentParser(
        description="Reproduce TP inconsistency bug"
    )
    parser.add_argument(
        "--tp", type=int, default=1, help="tensor_parallel_size (1 or 2)"
    )
    args = parser.parse_args()

    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model with tensor_parallel_size={args.tp}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=args.tp,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.6,
    )

    prompt = "The Eiffel Tower is in the city of"
    output_token = " Paris"
    token_id = vllm.tokenizer.encode(output_token)[0]

    target_layer = 1
    head_dim = 128

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            with tracer.invoke(prompt):
                baseline_logit = (
                    vllm.logits.output[-1, token_id].item().save()
                )

    print(f"[TP={args.tp}] Baseline logit for '{output_token}': {baseline_logit}")

    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            all_logits = list().save()
            for target_head in range(2):
                with tracer.invoke(prompt):
                    head_in = (
                        vllm.model.layers[target_layer]
                        .self_attn.o_proj.input.clone()
                    )
                    start = target_head * head_dim
                    end = (target_head + 1) * head_dim
                    head_in[:, start:end] = 0
                    vllm.model.layers[target_layer].self_attn.o_proj.input = head_in
                    
                    all_logits.append(vllm.logits.output[-1, token_id].item().save())

    for target_head, logits in enumerate(all_logits):
        print(
            f"[TP={args.tp}] Intervened logit "
            f"(layer={target_layer}, head={target_head} zeroed): {logits}"
        )
        print(f"[TP={args.tp}] Difference: {baseline_logit - logits}")
        print()


if __name__ == "__main__":
    main()
```

For `--tp 1`, I get:

```text
[TP=1] Intervened logit (layer=1, head=0 zeroed): 16.5
[TP=1] Difference: -0.015625

[TP=1] Intervened logit (layer=1, head=1 zeroed): 16.453125
[TP=1] Difference: 0.03125
```

For `--tp 2`, I get:

```text
[TP=2] Logits for ' Paris' (layer 1): 16.515625
[TP=2] Intervened logit (layer=1, head=0 zeroed): 16.515625
[TP=2] Difference: -0.03125

[TP=2] Logits for ' Paris' (layer 1): 12.703125
[TP=2] Intervened logit (layer=1, head=1 zeroed): 12.703125
[TP=2] Difference: 3.78125
```

This still seems problematic to me, because the TP=2 intervention results are not consistent with TP=1, and the second TP=2 value in particular looks far outside the range of normal numerical variation.

My current suspicion is that this may be a separate issue related to logits gathering or sharded outputs under TP > 1, rather than the original synchronization bug that the PR fixed.

---

## Question

Would you prefer that I open two new issues for these follow-up cases?

My current impression is:

1. the PR fixes the original unstable-logit / synchronization issue;
2. but there may still be:
   - a separate cross-trace activation device-placement bug, and
   - a separate TP>1 logits/intervention consistency bug.

**Comment by JadenFiotto-Kaufman** [comment]
Okay I'll add the extra cuda sync before the logits.

For 1.) I don't think that's something I can handle. I'd do:

original_device = vllm.model.layers[layer_index].self_attn.o_proj.input.device

vllm.model.layers[layer_index].self_attn.o_proj.input = cached.to(device) 

2.) I'll look into it. If you could aggregate this over some multiple runs to make sure it's not just noise that would be helpful.

**Comment by cwdghh** [comment]
@JadenFiotto-Kaufman Thanks again for you support — your suggested workaround for (1) does work on my side.

I changed the patching line to move the cached activation onto the current module input device before reusing it:

```python
device = vllm.model.layers[layer_index].self_attn.o_proj.input.device
vllm.model.layers[layer_index].self_attn.o_proj.input = reference_activation_cache.detach().to(device)
```

With that change, the cross-trace activation reuse case runs successfully without the device mismatch error.

So I think that part is resolved for my use case — thanks for the suggestion.

My current understanding is that under TP, the cached activation is not automatically aligned to the shard-local device when reused across traces, so an explicit `.to(current_device)` is needed.

---

For (2), I’ll run a more systematic comparison to check whether the TP=1 vs TP=2 discrepancy is real and stable rather than just noise. I’m planning to repeat the experiment across multiple runs to compare the aggregated results.

## Minimal reproduction

```python
import argparse
import torch
from nnsight.modeling.vllm import VLLM


@torch.inference_mode()
def main():
    parser = argparse.ArgumentParser(
        description="Reproduce TP inconsistency bug"
    )
    parser.add_argument(
        "--tp", type=int, default=1, help="tensor_parallel_size (1 or 2)"
    )
    args = parser.parse_args()

    model_path = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
    print(f"Loading model with tensor_parallel_size={args.tp}")
    vllm = VLLM(
        model_path,
        tensor_parallel_size=args.tp,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.6,
    )

    prompt = "The Eiffel Tower is in the city of"
    output_token = " Paris"
    token_id = vllm.tokenizer.encode(output_token)[0]

    target_layer = 0
    num_heads = 2
    head_dim = 128

    # Test 1: baseline
    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            with tracer.invoke(prompt):
                baseline_logit = (
                    vllm.logits.output[-1, token_id].item().save()
                )

    print(f"[TP={args.tp}] Baseline logit for '{output_token}': {baseline_logit}")

    # Test 2: zero out attention heads (one per invoke)
    with torch.no_grad():
        with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
            all_logits = list().save()
            for target_head in range(num_heads):
                with tracer.invoke(prompt):
                    head_in = (
                        vllm.model.layers[target_layer]
                        .self_attn.o_proj.input.clone()
                    )
                    start = target_head * head_dim
                    end = (target_head + 1) * head_dim
                    head_in[:, start:end] = 0
                    vllm.model.layers[target_layer].self_attn.o_proj.input = head_in
                    
                    all_logits.append(vllm.logits.output[-1, token_id].item().save())

    for target_head, logits in enumerate(all_logits):
        print(
            f"[TP={args.tp}] Intervened logit "
            f"(layer={target_layer}, head={target_head} zeroed): {logits}"
        )
        print(f"[TP={args.tp}] Difference: {baseline_logit - logits}")
        print()
    
    print(
        "Compare these values between --tp 1 and --tp 2. "
        "They should match but don't."
    )


if __name__ == "__main__":
    main()
```

## What I expected

For a fixed model, prompt, layer, and intervention, I expected the intervention results to be the same (or at least very close) when changing only `tensor_parallel_size`.

At minimum, I expected repeated runs under the same `tensor_parallel_size=2` setting to be stable.

## What I observed

When I repeat the exact same script multiple times with `tensor_parallel_size=2`, I sometimes get the expected-looking result, but sometimes one of the intervention outputs becomes clearly wrong.

For example, across repeated runs with `num_heads=2`, I observed:

### Run 1

```text
[TP=2] Intervened logit (layer=0, head=0 zeroed): 16.453125
[TP=2] Difference: 0.03125

[TP=2] Intervened logit (layer=0, head=1 zeroed): -0.14697265625
[TP=2] Difference: 16.63134765625
```

### Run 2

```text
[TP=2] Intervened logit (layer=0, head=0 zeroed): 16.453125
[TP=2] Difference: 0.03125

[TP=2] Intervened logit (layer=0, head=1 zeroed): 16.4375
[TP=2] Difference: 0.046875
```

### Run 3

```text
[TP=2] Intervened logit (layer=0, head=0 zeroed): 16.453125
[TP=2] Difference: 0.03125

[TP=2] Intervened logit (layer=0, head=1 zeroed): 16.4375
[TP=2] Difference: 0.046875
```

The `head=1` result in Run 1 looks clearly incorrect compared with the later runs. This makes the issue appear intermittent / non-deterministic rather than just a consistent TP-size shift.

## Why this seems problematic

This does not look like normal floating-point noise:

- the stable runs give values around `16.4`
- but the anomalous run gives `-0.14697265625` for the same intervention
- that is a very large difference in magnitude, not a small numerical perturbation

So at least from my side, this still looks like some remaining TP-related tracing / gathering / synchronization issue under `dispatch=True`, even after the earlier synchronization fix.

---

**P.S.** I originally noticed this while running a simple activation patching script: if I changed only `tensor_parallel_size` from `1` to `2` and kept everything else identical, the intervention results sometimes differed significantly. I then extracted the following minimal script to reproduce the issue.

**Head Importance Result when TP=1**:
<img width="3293" height="2647" alt="Image" src="https://github.com/user-attachments/assets/0c660586-664e-4a30-8055-5dca5b1be8e1" />

**Head Importance Result when TP=2**:
<img width="3267" height="2647" alt="Image" src="https://github.com/user-attachments/assets/3d875e06-640d-48ff-bb1a-58c0205d3356" />

**Comment by JadenFiotto-Kaufman** [comment]
@cwdghh  Can you give the branch a try now?

**Comment by cwdghh** [comment]
@JadenFiotto-Kaufman Sorry for the delayed reply, and thanks for pointing me to commit `2cdd313f9669bbe1f4466b71e1ad5fbdeba4ec61`.

I switched to that version and wrote a more systematic test script to check whether the remaining TP=1 vs TP=2 intervention discrepancy is real or just noise. The script repeats the intervention multiple times, aggregates the results, and reports per-head mean/std.

Here is the script I used:

```python
"""
Minimal reproduction: Inconsistent intervention results between
tensor_parallel_size=1 and tensor_parallel_size=2.

Usage:
    python repro_bug2_tp_inconsistency.py --tp 1 --runs 5
    python repro_bug2_tp_inconsistency.py --tp 2 --runs 5
    python repro_bug2_tp_inconsistency.py --tp 1 2 --runs 5   # run both and compare
"""

import argparse
import json
import statistics
import torch
from pathlib import Path
from tabulate import tabulate
from nnsight.modeling.vllm import VLLM


MODEL_PATH   = "/mnt/workspace/models/public/Qwen/Qwen2.5/Qwen2.5-7B-Instruct/"
PROMPT       = "After John and Mary went to the store, Mary gave a bottle of milk to"
OUTPUT_TOKEN = " John"
TARGET_LAYER = 24
NUM_HEADS    = 28
START_INDEX  = 20
HEAD_DIM     = 128
CACHE_DIR    = Path("/tmp/tp_repro_cache")


@torch.inference_mode()
def run_single_tp(tp: int, runs: int) -> dict:
    print(f"\n{'='*60}")
    print(f"  Loading model  tensor_parallel_size={tp}")
    print(f"{'='*60}")

    vllm = VLLM(
        MODEL_PATH,
        tensor_parallel_size=tp,
        dispatch=True,
        dtype=torch.float16,
        gpu_memory_utilization=0.6,
    )

    token_id = vllm.tokenizer.encode(OUTPUT_TOKEN)[0]
    results  = {"tp": tp, "baseline": [], "heads": {h: [] for h in range(START_INDEX, NUM_HEADS)}}

    for run_idx in range(runs):
        print(f"\n[TP={tp}] Run {run_idx + 1}/{runs}")

        with torch.no_grad():
            with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
                with tracer.invoke(PROMPT):
                    baseline_logit = vllm.logits.output[-1, token_id].item().save()

        bl = float(baseline_logit)
        results["baseline"].append(bl)
        print(f"  Baseline logit: {bl:.6f}")

        with torch.no_grad():
            with vllm.trace(temperature=0.0, max_tokens=1) as tracer:
                saved = dict().save()
                for head in range(START_INDEX, NUM_HEADS):
                    with tracer.invoke(PROMPT):
                        head_in = (
                            vllm.model.layers[TARGET_LAYER]
                            .self_attn.o_proj.input.clone()
                        )
                        s, e = head * HEAD_DIM, (head + 1) * HEAD_DIM
                        head_in[:, s:e] = 0
                        vllm.model.layers[TARGET_LAYER].self_attn.o_proj.input = head_in
                        saved[head] = vllm.logits.output[-1, token_id].item().save()

        for head, sv in saved.items():
            v = float(sv)
            results["heads"][head].append(v)
            diff = bl - v
            print(f"  head={head:2d}  logit={v:.6f}  diff={diff:+.6f}")

    del vllm
    torch.cuda.empty_cache()

    return results


def stats(values: list[float]) -> tuple[float, float]:
    mean = statistics.mean(values)
    std  = statistics.pstdev(values)
    return mean, std


def print_comparison_table(res1: dict, res2: dict) -> None:
    tp1, tp2 = res1["tp"], res2["tp"]

    bl1_mean, bl1_std = stats(res1["baseline"])
    bl2_mean, bl2_std = stats(res2["baseline"])

    print(f"\n{'─'*80}")
    print(f"  Baseline logit  (token='{OUTPUT_TOKEN}')")
    print(f"{'─'*80}")
    bl_table = [
        [f"TP={tp1}", f"{bl1_mean:.6f}", f"{bl1_std:.6f}", "—"],
        [f"TP={tp2}", f"{bl2_mean:.6f}", f"{bl2_std:.6f}", f"{bl2_mean - bl1_mean:+.6f}"],
    ]
    print(tabulate(
        bl_table,
        headers=["Config", "Mean logit", "Std (across runs)", f"Δ vs TP={tp1}"],
        tablefmt="fancy_grid",
        floatfmt=".6f",
    ))

    print(f"\n{'─'*80}")
    print(f"  Intervention logits  (layer={TARGET_LAYER}, one head zeroed per row)")
    print(f"{'─'*80}")

    rows = []
    for head in range(START_INDEX, NUM_HEADS):
        m1, s1 = stats(res1["heads"][head])
        m2, s2 = stats(res2["heads"][head])

        eff1 = bl1_mean - m1
        eff2 = bl2_mean - m2

        uncertain = "⚠" if s2 > 1e-4 else ""

        rows.append([
            head,
            f"{m1:.6f}",
            f"{s1:.6f}",
            f"{eff1:+.6f}",
            f"{m2:.6f}",
            f"{s2:.6f}",
            f"{eff2:+.6f}",
            f"{m2 - m1:+.6f}",
            uncertain,
        ])

    headers = [
        "Head",
        f"TP={tp1} mean", f"TP={tp1} std", f"TP={tp1} effect",
        f"TP={tp2} mean", f"TP={tp2} std", f"TP={tp2} effect",
        "Δ mean",
        "Unstable?",
    ]
    print(tabulate(rows, headers=headers, tablefmt="fancy_grid"))

    unstable_heads = [
        head for head in range(START_INDEX, NUM_HEADS)
        if stats(res2["heads"][head])[1] > 1e-4
    ]
    print(f"\n  TP={tp2} unstable heads (std > 1e-4): {unstable_heads if unstable_heads else 'none'}")
    max_delta = max(abs(stats(res2["heads"][h])[0] - stats(res1["heads"][h])[0])
                    for h in range(START_INDEX, NUM_HEADS))
    print(f"  Max |mean(TP={tp2}) − mean(TP={tp1})| across heads: {max_delta:.6f}")


def cache_path(tp: int) -> Path:
    CACHE_DIR.mkdir(exist_ok=True)
    return CACHE_DIR / f"tp{tp}_results.json"


def save_results(res: dict) -> None:
    p = cache_path(res["tp"])
    serialisable = {
        "tp":       res["tp"],
        "baseline": res["baseline"],
        "heads":    {str(k): v for k, v in res["heads"].items()},
    }
    p.write_text(json.dumps(serialisable, indent=2))
    print(f"  Results cached → {p}")


def load_results(tp: int) -> dict | None:
    p = cache_path(tp)
    if not p.exists():
        return None
    raw = json.loads(p.read_text())
    raw["heads"] = {int(k): v for k, v in raw["heads"].items()}
    print(f"  Loaded cached results from {p}")
    return raw


def main() -> None:
    parser = argparse.ArgumentParser(description="TP inconsistency reproducer")
    parser.add_argument(
        "--tp", type=int, nargs="+", default=[1, 2],
        help="tensor_parallel_size values to test, e.g. --tp 1 2",
    )
    parser.add_argument(
        "--runs", type=int, default=3,
        help="Number of times to repeat each experiment (to measure variance)",
    )
    parser.add_argument(
        "--no-cache", action="store_true",
        help="Ignore cached results and re-run everything",
    )
    args = parser.parse_args()

    all_results: dict[int, dict] = {}

    for tp in args.tp:
        cached = None if args.no_cache else load_results(tp)
        if cached is not None:
            all_results[tp] = cached
        else:
            res = run_single_tp(tp, runs=args.runs)
            save_results(res)
            all_results[tp] = res

    if len(all_results) >= 2:
        tp_list = sorted(all_results.keys())
        print_comparison_table(all_results[tp_list[0]], all_results[tp_list[1]])
    else:
        tp = list(all_results.keys())[0]
        res = all_results[tp]
        bl_mean, bl_std = stats(res["baseline"])
        rows = []
        for head in range(START_INDEX, NUM_HEADS):
            m, s = stats(res["heads"][head])
            rows.append([head, f"{m:.6f}", f"{s:.6f}", f"{bl_mean - m:+.6f}"])
        print(f"\nBaseline: mean={bl_mean:.6f}  std={bl_std:.6f}")
        print(tabulate(rows,
                       headers=["Head", "Mean logit", "Std", "Effect"],
                       tablefmt="fancy_grid"))


if __name__ == "__main__":
    main()
```

Here is the summary I got:

```text
Baseline logit  (token=' John')

TP=1 mean: 11.531250, std: 0.000000
TP=2 mean: 11.539062, std: 0.000000
Δ vs TP=1: +0.007812
```

So the baseline itself looks essentially stable and consistent.

However, for the intervention runs (zeroing one head at a time in layer 24), I still see instability under `TP=2` for some heads:

- head 21:
  - `TP=1 mean = 11.5312`, `std = 0`
  - `TP=2 mean = 11.9750`, `std = 0.91875`
- head 22:
  - `TP=1 mean = 11.1328`, `std = 0`
  - `TP=2 mean = 11.6109`, `std = 0.971875`

The script flagged these as unstable:
- `TP=2 unstable heads (std > 1e-4): [21, 22]`

And the maximum mean discrepancy across heads was:

```text
Max |mean(TP=2) − mean(TP=1)| across heads: 0.478125
```

<img width="1057" height="507" alt="Image" src="https://github.com/user-attachments/assets/e27fb456-ac8e-4692-b37c-5c76c01187fa" />

So from my side, the current picture seems to be:

1. the baseline logits are stable and nearly identical between TP=1 and TP=2;
2. but some intervention results under TP=2 are still unstable across runs;
3. and for those heads, the TP=2 intervention values differ from TP=1 by much more than I would expect from normal numerical noise.

This is also consistent with what I originally observed in my larger activation patching experiments: changing only `tensor_parallel_size` produced visibly different head-importance heatmaps, and reducing the setup led to the script above.

So at this point, it seems that the recent fixes may have resolved the baseline/logit-read instability, but there may still be a remaining issue specifically affecting intervention behavior under TP>1.

**Comment by khaiwang** [comment]
Hi @cwdghh, can you try this pr and see whether it works for you?

**Comment by cwdghh** [comment]
@khaiwang Thanks — I tested the PR on my end, and it appears to fix the issue. ❤️ 

After switching to the PR version, I reran the intervention script that was previously showing unstable results under `tensor_parallel_size=2`. With this patch, the outputs are now stable across repeated runs, and the TP=1 vs TP=2 differences are reduced to the small range I would expect from normal numerical variation.

Thanks again for the detailed investigation and fix — I really appreciate it.

From my side, this resolves the issue, so I think it can be closed.

**Comment by Butanium** [comment]
Thank you for helping the team with all your testing @cwdghh!
